version: '3'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: docker/app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:80"
    networks:
      - site

  db:
    container_name: mysql
    build:
      context: ./
      dockerfile: docker/sql.docker
    restart: always
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
    networks:
      - site

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - "PMA_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=secret"
    networks:
      - site
    ports:
      - "8080:80"

networks:
  site:
